### ISSUE TITLE
Selecting emojis don't reflect in Editor state

### ISSUE THREAD

**Issue by AntwanSherif** [zamarawka/draft-js-emoji-mart-plugin#1]
Hi, I like this library, it saves a lot of time and effort.

But one thing I need help with is that on selecting an emoji, the Editor state is not updated.
Am I doing something wrong here? Or shall I manage that selection manually?

**Comment by zamarawka** [comment]
Hi! Thank you for your feedback.

It looks like you got some problems with binding emoji-mart picker to Draft.js state. To handle this you should use provided by plugin factory picker

Take a look at this part of "Usage" from readme.md:

```js
const emojiPlugin = createEmojiMartPlugin({
  data,
  set: 'apple'
});

// NimblePicker from emoji-mart binded with draftjs
const { Picker } = emojiPlugin; // <<< Use this component instead of emoji-mart, it already binded to editor state
```
