### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by euphocat** [zamarawka/draft-js-emoji-mart-plugin#2]
Hello ! I found your repo and I was disappointed not to find the TS typings. I realized it was written using flow. I've tried and succeed to write a TS version of it. Would you be interested in a PR ?

**Comment by zamarawka** [comment]
Hello! Thank you for your interest.

I got some free time at now, so I decide to fresh up my old repos and maybe publish some new packages.
So, I did it by myself. As result first non beta version of package. Check out last release, there is a some fixes and improvements. 

Sorry for delay.
