### ISSUE TITLE
Wrong skin

### ISSUE THREAD

**Issue by antonazgarovich** [zamarawka/draft-js-emoji-mart-plugin#4]
After choosing a skin color. The color is not set in the editor.
https://zamarawka.github.io/draft-js-emoji-mart-plugin/?path=/story/customeditor--base

<img width="461" alt="Снимок экрана 2021-02-26 в 16 06 23" src="https://user-images.githubusercontent.com/8579262/109292779-b685c600-784c-11eb-98b1-2c5a64e32f03.png">

**Comment by zamarawka** [comment]
Oops, looks like some version miss match around emoji-regexp and emoji-mart, maybe.
Usually I use it with disabled skin colors, so don't tested this case.

I'm too busy at now and don't have enough time to fix this.
If you have some ideas how to fix this feel free to PR. ✌️
Let's make this fully work 😊

**Comment by antonazgarovich** [comment]
https://github.com/zamarawka/draft-js-emoji-mart-plugin/pull/6

**Comment by antonazgarovich** [comment]
Here's the PR. I apologize if I am in a hurry, but if you have the ability to publish the library faster, I would appreciate it. If you have time, of course. I just need to fix this issue in the project in the near future.

**Comment by zamarawka** [comment]
Fast fix - fast release. [v1.0.1](https://github.com/zamarawka/draft-js-emoji-mart-plugin/releases/tag/v1.0.1) already in npm.

Thank you! 👍

**Comment by nullablemind** [comment]
Thank you very much! 🎉
