### ISSUE TITLE
No default alignment of emojis in the text

### ISSUE THREAD

**Issue by antonazgarovich** [zamarawka/draft-js-emoji-mart-plugin#5]
When you install the application, the emojis are aligned down.

<img width="1267" alt="Снимок экрана 2021-02-26 в 16 26 30" src="https://user-images.githubusercontent.com/8579262/109294853-9277b400-784f-11eb-8e80-03d20e5ca5e6.png">

I suggest making the default alignment `vertical-align: bottom;`.
What do you think?

**Comment by zamarawka** [comment]
At now this plugin don't provide own styles for include, there is no plans for this. I prefer provide styles agnostic packages.
Basicly, draft-js-plugins use for creation custom editors. In my experience, every custom editor developing start from styling, so, I don't see any problems for do it by yourself ☺️

Thanks for your feedback 😉
